#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorRF,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     NoMotor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorRM,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorRB,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_1,     motorLF,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     motorTurnCam,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     motorLM,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_2,     motorLB,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoTiltCam,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servoRF,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servoLF,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servoRB,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servoLB,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    NoServo,              tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int cameraPosition = 0;
int cameraRight = 5;
int cameraLeft = -5;

void forward(int x, int wait);
void backward(int x, int wait);
void enterTurnMode();
void exitTurnMode();
void turnLeft(int x, int wait);
void turnRight(int x, int wait);
void camera(int wait, int speed);
void cameraVertical(int x);1
void halt();

task main()
{
	forward(100,1000);
	turnLeft(100,1500);
	forward(100,1000);
}

void enterTurnMode()
{
	servo[servoLF] = 36;
	servo[servoLB] = 208;
	servo[servoRF] = 216;
	servo[servoRB] = 48;

	wait1Msec(1500);
}

void exitTurnMode()
{

	servo[servoLF] = 128;
	servo[servoLB] = 128;
	servo[servoRF] = 128;
	servo[servoRB] = 128;

	wait1Msec(1500);
}

void forward(int x, int wait)
{
	motor[motorRF] = x;
	motor[motorRM] = x;
	motor[motorRB] = x;

	motor[motorLF] = x;
	motor[motorLM] = x;
	motor[motorLB] = x;

	wait1Msec(wait);

	halt();
}

void backward(int x, int wait)
{
	motor[motorRF] = -x;
	motor[motorRM] = -x;
	motor[motorRB] = -x;

	motor[motorLF] = -x;
	motor[motorLM] = -x;
	motor[motorLB] = -x;

	wait1Msec(wait);

	halt();
}

void camera(int wait, int speed)
{
	int switchTrack;
	if(speed < 0)
	{
		switchTrack = -1;
	} else
	{
		switchTrack = 1;
	}

	if (cameraPosition + wait * switchTrack > 1350)
	{
		wait = 1350 - cameraPosition;
	} (cameraPosition + wait * switchTrack < -1350)
	{
		wait = - 1350 - cameraPosition;
	}

	motor[motorTurnCam] = speed;

	wait1Msec(wait);

	motor[motorTurnCam] = 0;
}

void turnLeft(int x, int wait)
{
	enterTurnMode();

	motor[motorRF] = x;
	motor[motorRB] = x;
	motor[motorRM] = x;
	motor[motorLF] = -x;
	motor[motorLB] = -x;
	motor[motorLM] = -x;
	wait1Msec(wait);

	halt();

	exitTurnMode();
}

void turnRight(int x, int wait)
{
	enterTurnMode();

	motor[motorRF] = -x;
	motor[motorRB] = -x;
	motor[motorRM] = -x
	motor[motorLF] = x;
	motor[motorLB] = x;
	motor[motorLM] = x;
	wait1Msec(wait);

	halt();

	exitTurnMode();
}

void cameraVertical(int x)
{
		servo[servoTiltCam] = x;
}

void halt()
{
	motor[motorRF] = 0;
	motor[motorRM] = 0;
	motor[motorRB] = 0;

	motor[motorLF] = 0;
	motor[motorLM] = 0;
	motor[motorLB] = 0;
}
